# Generated by Django 5.2.9 on 2025-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['page', 'order', 'slug']},
        ),
        migrations.AddField(
            model_name='contentblock',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='page',
            field=models.CharField(default='home', help_text='Page where this block appears', max_length=100),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['page', 'order'], name='cms_content_page_7c0174_idx'),
        ),
    ]
