# Generated by Django 5.2.9 on 2025-12-05 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('document_category', models.CharField(default='investor', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('download_count', models.IntegerField(default=0)),
                ('max_downloads', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
